default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: tracker_development

test:
  <<: *default
  database: tracker_test

production:
  <<: *default
  database: tracker_production
  username: tracker
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
